# Generated by Django 3.2.6 on 2021-08-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255, verbose_name='Nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobrenome_contato', models.CharField(blank=True, max_length=255, verbose_name='Sobrenome')),
                ('telefone_contato', models.CharField(max_length=12, verbose_name='Telefone')),
                ('email_contato', models.CharField(blank=True, max_length=255, verbose_name='E-mail')),
                ('data_criacao_contato', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('descricao_contato', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria_contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contatos.categoria')),
            ],
        ),
    ]
