# Generated by Django 3.2.6 on 2021-08-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0002_auto_20210817_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='descricao_contato',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
