# Generated by Django 3.2.6 on 2021-08-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0007_alter_contato_categoria_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria_contato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Contatos.categoria', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
