# Generated by Django 3.2.6 on 2021-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0009_alter_contato_categoria_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=225, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone_contato',
            field=models.CharField(max_length=225, verbose_name='Telefone'),
        ),
    ]
