# Generated by Django 3.2.6 on 2021-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0011_alter_contato_categoria_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome_contato',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='sobrenome_contato',
            field=models.CharField(max_length=100, verbose_name='Sobrenome'),
        ),
    ]
