# Generated by Django 3.2.6 on 2021-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0015_contato_image_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='image_contact',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
